"use client";

import { ArrowLink, Eyebrow, ExternalLink, SectionLabel } from "@/components/ui";
import { useLanguage } from "@/components/language";

export default function QuantumCircuitPage() {
  const { language } = useLanguage();
  const uz = language === "uz";
  return <><section className="product-hero container cyan-product"><div className="product-copy"><Eyebrow>02 / BROWSER DIAGNOSTICS</Eyebrow><h1>Quantum <span>Circuit</span></h1><p>{uz ? "Kichik circuitlarda entanglement qayerda o‘sishini tushuntiradigan, browser’da lokal ishlaydigan open-source vosita." : "An open-source browser tool that explains where entanglement grows in small circuits, running locally in the browser."}</p><div className="hero-actions"><ExternalLink href="https://github.com/quantum-axion-20260905/Quantum-Circuit">GitHub repository</ExternalLink><ArrowLink href="/tutorials" secondary>{uz ? "Tutorialni boshlash" : "Start a tutorial"}</ArrowLink></div></div><div className="circuit-visual"><div className="circuit-header"><span>LOCAL ANALYSIS</span><strong>QUBITS 04</strong></div>{["q₀", "q₁", "q₂", "q₃"].map((q, row) => <div className="circuit-row" key={q}><span>{q}</span><i /><i className={row === 0 ? "gate h" : "gate blank"}>{row === 0 ? "H" : ""}</i><i className={row === 0 || row === 1 ? "gate cx" : "gate blank"}>{row === 0 ? "●" : row === 1 ? "⊕" : ""}</i><i /><i /><b /></div>)}<div className="entropy-chip">PEAK ENTROPY <strong>1.00 bit</strong></div></div></section><section className="section container feature-columns"><div><SectionLabel>WHAT IT SHOWS</SectionLabel><h2>{uz ? "Murakkablikni intuitiv ko‘ring." : "See complexity intuitively."}</h2><p>{uz ? "Quantum Circuit OpenQASM 2.0 subsetini qabul qiladi, statevector’ni Web Worker’da hisoblaydi va har bir contiguous cut uchun Von Neumann entropy’ni ko‘rsatadi." : "Quantum Circuit accepts a documented OpenQASM 2.0 subset, computes the statevector in a Web Worker and reports Von Neumann entropy for every contiguous cut."}</p></div><div className="metric-grid"><div><strong>10</strong><span>{uz ? "qubitgacha" : "qubits max"}</span></div><div><strong>0</strong><span>{uz ? "backend upload" : "backend uploads"}</span></div><div><strong>JSON</strong><span>{uz ? "reproducible report" : "reproducible report"}</span></div><div><strong>MIT</strong><span>{uz ? "open source" : "open source"}</span></div></div></section><section className="section container limitation-note"><SectionLabel>HONEST SCOPE</SectionLabel><h2>{uz ? "Kichik circuitlar uchun aniq va tushunarli." : "Precise and understandable for small circuits."}</h2><p>{uz ? "Bu production-scale simulator yoki hardware runtime predictor emas. Uning kuchi — foydalanuvchiga qaysi gate, layer yoki cut’ni keyin tekshirish kerakligini ko‘rsatish." : "This is not a production-scale simulator or a hardware runtime predictor. Its strength is showing which gate, layer or cut a user should inspect next."}</p></section></>;
}
