"use client";

import Link from "next/link";
import { PageIntro, SectionLabel } from "@/components/ui";
import { useLanguage } from "@/components/language";

export default function ProjectsPage() {
  const { language } = useLanguage();
  const uz = language === "uz";
  return <><PageIntro eyebrow={uz ? "PORTFOLIO · 02 LOYIHA" : "PORTFOLIO · 02 PROJECTS"} title={uz ? <>Tadqiqot uchun <span className="gradient-text">to‘g‘ri qatlam.</span></> : <>The right layer for <span className="gradient-text">research.</span></>} description={uz ? "Quantum Axion bir-birini takrorlamaydigan, lekin birgalikda kuchliroq bo‘ladigan ikkita open-source vositani ishlab chiqadi." : "Quantum Axion develops two open-source tools that do not duplicate each other — but become stronger together."} /><section className="section container project-list"><Link className="project-row violet" href="/projects/ket-studio"><span className="row-number">01</span><div className="row-mark">◈</div><div className="row-main"><SectionLabel>DESKTOP RESEARCH WORKSPACE</SectionLabel><h2>KET Studio</h2><p>{uz ? "Python, haqiqiy terminal va event-driven vizualizatsiya bilan kvant tajribalarini desktop’da qurish, ishlatish va saqlash muhiti." : "A desktop environment for building, running and archiving quantum experiments with Python, a real terminal and event-driven visualization."}</p><div className="row-tags"><span>Flutter</span><span>Python</span><span>Windows</span></div></div><span className="row-arrow">→</span></Link><Link className="project-row cyan" href="/projects/quantum-circuit"><span className="row-number">02</span><div className="row-mark">⌁</div><div className="row-main"><SectionLabel>BROWSER DIAGNOSTICS</SectionLabel><h2>Quantum Circuit</h2><p>{uz ? "OpenQASM circuitlarini o‘rnatishsiz tahlil qiladigan, entropy va entanglement o‘sishini vizual tushuntiradigan web vosita." : "A zero-install web tool for analyzing OpenQASM circuits and visually explaining entropy and entanglement growth."}</p><div className="row-tags"><span>Next.js</span><span>TypeScript</span><span>Local-first</span></div></div><span className="row-arrow">→</span></Link></section><section className="section container compatibility"><SectionLabel>INTEROPERABILITY</SectionLabel><h2>{uz ? "Mustaqil. Moslashuvchan. Ochiq." : "Independent. Interoperable. Open."}</h2><p>{uz ? "Ikkala loyiha OpenQASM va versioned JSON contract orqali data almashadi. Bu foydalanuvchiga browser’da boshlash, desktop’da davom ettirish va natijani yana browser’da tekshirish imkonini beradi." : "Both projects can exchange data through OpenQASM and a versioned JSON contract. Users can start in the browser, continue on desktop and verify the result back in the browser."}</p></section></>;
}
