"use client";

import Link from "next/link";
import { PageIntro, SectionLabel } from "@/components/ui";
import { useLanguage } from "@/components/language";

export default function ProjectsPage() {
  const { language } = useLanguage();
  const uz = language === "uz";
  return <><PageIntro eyebrow={uz ? "PRODUCT · 01 LOYIHA" : "PRODUCT · ONE PROJECT"} title={uz ? <>Tadqiqot uchun <span className="gradient-text">to‘liq ish muhiti.</span></> : <>A complete workspace for <span className="gradient-text">research.</span></>} description={uz ? "KET Studio kod, haqiqiy terminal, vizual natija va session tarixini bitta Windows desktop workflow’iga birlashtiradi." : "KET Studio brings code, a real terminal, visual output and session history into one Windows desktop workflow."} /><section className="section container project-list"><Link className="project-row violet" href="/projects/ket-studio"><span className="row-number">01</span><div className="row-mark">◈</div><div className="row-main"><SectionLabel>DESKTOP RESEARCH WORKSPACE</SectionLabel><h2>KET Studio</h2><p>{uz ? "Python tajribalarini yozing, ishga tushiring, event-driven vizuallarni oling va natijani qayta tiklash uchun kerakli izlarni saqlang." : "Write and run Python experiments, receive event-driven visuals and keep the traces needed to reproduce a result."}</p><div className="row-tags"><span>Flutter</span><span>Python</span><span>Windows 10/11</span><span>MSIX</span></div></div><span className="row-arrow">→</span></Link></section><section className="section container compatibility"><SectionLabel>RELEASE SCOPE</SectionLabel><h2>{uz ? "Aniq va halol platforma va’dasi." : "A precise platform promise."}</h2><p>{uz ? "Windows 10/11 x64 hozirgi qo‘llab-quvvatlanadigan release’dir. Linux va macOS keyingi bosqich uchun rejalashtirilgan, ammo hozir installer yoki production support sifatida taqdim etilmaydi." : "Windows 10/11 x64 is the supported release today. Linux and macOS are planned next, but are not presented as installers or production support yet."}</p><div className="platform-grid"><div className="platform-card available"><span>WINDOWS</span><strong>10/11 · x64</strong><small>{uz ? "MSIX va EXE mavjud" : "MSIX and EXE available"}</small></div><div className="platform-card"><span>LINUX</span><strong>Roadmap</strong><small>{uz ? "Build va PTY QA kutilmoqda" : "Build and PTY QA pending"}</small></div><div className="platform-card"><span>MACOS</span><strong>Roadmap</strong><small>{uz ? "Build va PTY QA kutilmoqda" : "Build and PTY QA pending"}</small></div></div></section></>;
}
