"use client";

import { PageIntro, SectionLabel } from "@/components/ui";
import { useLanguage } from "@/components/language";

export default function GrantsPage() {
  const { language } = useLanguage();
  const uz = language === "uz";
  return <><PageIntro eyebrow="OPEN-SOURCE · GRANT POSITIONING" title={uz ? <>Bitta loyiha. <span className="gradient-text">Aniq deliverable’lar.</span></> : <>One project. <span className="gradient-text">Clear deliverables.</span></>} description={uz ? "KET Studio grant scope’i real desktop workflow’ini research-grade reproducibility, provenance, validation va distribution bilan kuchaytirishga qaratilgan." : "KET Studio’s grant scope strengthens a real desktop workflow with research-grade reproducibility, provenance, validation and distribution."} /><section className="section container grant-grid"><article className="grant-card violet"><div className="grant-card-top"><span>WORKSTREAM 01</span><span>P0</span></div><h2>Reliable runs</h2><p>{uz ? "Har bir tajriba qaysi kod, environment va parametrlar bilan ishlaganini qayta tekshirish mumkin bo‘ladi." : "Make every run traceable to its code, environment and parameters."}</p><div className="grant-deliverables"><strong>{uz ? "Natijalar" : "Deliverables"}</strong><span>{uz ? "Manifest va script hash" : "Manifest and script hash"}</span><span>{uz ? "Pinned Python dependencies" : "Pinned Python dependencies"}</span><span>{uz ? "Raw result va event archive" : "Raw result and event archive"}</span></div></article><article className="grant-card cyan"><div className="grant-card-top"><span>WORKSTREAM 02</span><span>P1</span></div><h2>Research UX</h2><p>{uz ? "Desktop tajribasini professional, tushunarli va jamoa bilan ulashishga qulay qilish." : "Make the desktop experience professional, understandable and easy to share with a research team."}</p><div className="grant-deliverables"><strong>{uz ? "Natijalar" : "Deliverables"}</strong><span>{uz ? "Run comparison va export" : "Run comparison and export"}</span><span>{uz ? "Accessibility va keyboard QA" : "Accessibility and keyboard QA"}</span><span>{uz ? "Signed Windows release" : "Signed Windows release"}</span></div></article></section><section className="section dark-panel"><div className="container statement"><SectionLabel>GRANT THESIS</SectionLabel><h2>{uz ? "Koddan natijagacha bo‘lgan yo‘lni ishonchli qilish." : "Make the path from code to result trustworthy."}</h2><p>{uz ? "KET Studio katta backend va’da qilmaydi. Uning qiymati — lokal execution, haqiqiy terminal, vizual evidence va provenance’ni bitta ochiq workflow’da birlashtirib, keyingi ilmiy tekshiruv uchun toza poydevor yaratish." : "KET Studio does not promise a backend it does not own. Its value is a clean open workflow that connects local execution, a real terminal, visual evidence and provenance for the next layer of scientific validation."}</p></div></section></>;
}
