"use client";

import { PageIntro, SectionLabel } from "@/components/ui";
import { useLanguage } from "@/components/language";

export default function GrantsPage() {
  const { language } = useLanguage();
  const uz = language === "uz";
  return <><PageIntro eyebrow="OPEN-SOURCE · GRANT POSITIONING" title={uz ? <>Har bir loyiha uchun <span className="gradient-text">aniq tezis.</span></> : <>A distinct thesis for <span className="gradient-text">each project.</span></>} description={uz ? "Quantum Axion loyihalari grantlarda bir-birini takrorlamaydi: birinchisi accessibility va physics intuition’ga, ikkinchisi research workflow’ga urg‘u beradi." : "Quantum Axion projects do not duplicate each other in grants: one focuses on accessibility and physics intuition, the other on research workflow."} /><section className="section container grant-grid"><article className="grant-card violet"><div className="grant-card-top"><span>GRANT A</span><span>01</span></div><h2>Quantum Circuit</h2><p>{uz ? "Browser’da ishlaydigan, o‘rnatishsiz va privacy-first entanglement diagnostikasi." : "A zero-install, privacy-first entanglement diagnostic that runs in the browser."}</p><div className="grant-deliverables"><strong>{uz ? "O‘lchanadigan natijalar" : "Measurable outcomes"}</strong><span>{uz ? "20+ reference circuit testlari" : "20+ reference circuit tests"}</span><span>{uz ? "3 ta open tutorial" : "3 open tutorials"}</span><span>{uz ? "Stable JSON report format" : "Stable JSON report format"}</span></div></article><article className="grant-card cyan"><div className="grant-card-top"><span>GRANT B</span><span>02</span></div><h2>KET Studio</h2><p>{uz ? "Kvant tajribalarini yozish, bajarish, vizuallashtirish va qayta tiklash uchun desktop research workspace." : "A desktop research workspace for writing, running, visualizing and reproducing quantum experiments."}</p><div className="grant-deliverables"><strong>{uz ? "O‘lchanadigan natijalar" : "Measurable outcomes"}</strong><span>{uz ? "Real terminal va Python workflow" : "Real terminal and Python workflow"}</span><span>{uz ? "Versioned event schema" : "Versioned event schema"}</span><span>{uz ? "Reproducible experiment archive" : "Reproducible experiment archive"}</span></div></article></section><section className="section dark-panel"><div className="container statement"><SectionLabel>SHARED DELIVERABLE</SectionLabel><h2>{uz ? "OpenQASM + JSON interoperability." : "OpenQASM + JSON interoperability."}</h2><p>{uz ? "Ikki grant orasidagi umumiy natija — foydalanuvchi browser’da boshlagan circuitini KET Studio’da davom ettira olishi va natijani yana web’da tekshira olishi." : "The shared outcome is an interoperability path: a user can start a circuit in the browser, continue in KET Studio and verify the result on the web again."}</p></div></section></>;
}
