"use client";

import { ArrowLink, Eyebrow, ExternalLink, SectionLabel } from "@/components/ui";
import { useLanguage } from "@/components/language";

export default function KetStudioPage() {
  const { language } = useLanguage();
  const uz = language === "uz";
  const features = uz ? ["Haqiqiy Windows terminali", "Python va virtual environment", "Event-driven visualization", "Session history va provenance"] : ["Real Windows terminal", "Python and virtual environments", "Event-driven visualization", "Session history and provenance"];
  return <><section className="product-hero container violet-product"><div className="product-copy"><Eyebrow>01 / DESKTOP RESEARCH WORKSPACE</Eyebrow><h1>KET <span>Studio</span></h1><p>{uz ? "Kvant hisoblash tajribalarini yozish, ishlatish, kuzatish va qayta tiklash uchun professional desktop ish muhiti." : "A professional desktop workspace for writing, running, observing and reproducing quantum computing experiments."}</p><div className="hero-actions"><ExternalLink href="https://github.com/quantum-axion-20260905/KET-Studio">GitHub repository</ExternalLink><ArrowLink href="/docs" secondary>{uz ? "Hujjatlarni o‘qish" : "Read the docs"}</ArrowLink></div></div><div className="product-screen"><div className="screen-bar"><span /><span /><span /><em>KET Studio / experiment.py</em></div><div className="screen-body"><div className="screen-sidebar"><i /><i /><i /><i /><i /></div><div className="screen-code"><small>01  import ket_viz</small><small>02  from qiskit import QuantumRegister</small><small>03</small><small>04  circuit = build_experiment(2)</small><small>05  circuit.h(0)</small><small>06  circuit.cx(0, 1)</small><small className="code-highlight">07  ket_viz.histogram(counts)</small><small>08</small><small>09  # visualize locally</small></div><div className="screen-chart"><div className="chart-bars"><i /><i /><i /><i /></div><small>LIVE OUTPUT</small></div></div></div></section><section className="section container feature-columns"><div><SectionLabel>WHAT IT DOES</SectionLabel><h2>{uz ? "Koddan vizual dalilgacha." : "From code to visual evidence."}</h2><p>{uz ? "KET Studio Python stdout oqimini event protocol orqali kuzatadi. Histogram, heatmap, chart, table, statevector va boshqa natijalar bitta research workspace’da ko‘rinadi." : "KET Studio observes Python stdout through an event protocol. Histograms, heatmaps, charts, tables, statevectors and other results appear in one research workspace."}</p></div><div className="feature-list">{features.map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong><i>↗</i></div>)}</div></section><section className="section dark-panel"><div className="container statement"><SectionLabel>GRANT THESIS</SectionLabel><h2>{uz ? "Desktop tadqiqot ishini tartibli va takrorlanadigan qilish." : "Making desktop research structured and reproducible."}</h2><p>{uz ? "KET Studio’ning qiymati faqat simulyatsiyada emas: u tajriba kodi, terminal oqimi, vizual natija va session tarixini bir workflow’ga yig‘adi." : "KET Studio’s value is not only simulation: it brings experiment code, terminal output, visual results and session history into one workflow."}</p></div></section></>;
}
